[package]
org = "i_deed"
name = "hikeG"
version = "0.1.0"
distribution = "2201.10.1"

[build-options]
observabilityIncluded = true

[[platform.java17.dependency]]
groupId = "org.mindrot"
artifactId = "jbcrypt"
version = "0.4"
